app = "movie-web-frontend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[build.args]
  NEXT_PUBLIC_BACKEND_API_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com/api/movies"
  NEXT_PUBLIC_API_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com/api"
  NEXT_PUBLIC_SOCKET_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com"
  NEXT_PUBLIC_IMAGE_PREFIX = "https://phimimg.com/"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXTAUTH_URL = "https://movie-web-frontend.fly.dev"
  NEXT_PUBLIC_BACKEND_API_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com/api/movies"
  NEXT_PUBLIC_API_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com/api"
  NEXT_PUBLIC_SOCKET_URL = "https://believe-cuts-mechanical-pulled.trycloudflare.com"
  NEXT_PUBLIC_IMAGE_PREFIX = "https://phimimg.com/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
